### ISSUE TITLE
Oauth loop at content page

### ISSUE THREAD

**Issue by eschwim** [sayakb/sticky-notes#183]
Hi Sayak!

First, please let me complement you on Sticky Notes.  It is much easier to install and more aesthetically pleasing than the rest of the open source/hostable pastebin replacements.

However, I am having trouble getting OAuth working properly.  I've generated and entered the client ID and client secret, and set the redirect uri and javascript origin in the developer console.  When I enable Oauth and attempt to authenticate, I am sent through the usual Oauth grant process.  However, when I arrive at the consent page and click 'Accept', I am bounced right back to the same consent page.

Looking in firebug, I can see the usual 302 redirects going on in the background.  When clicking the Accept button, I get bounced to `https://<myhost>/user/login?code=<auth token>`, which then immediately 302 redirects me back to the OAuth2 login page.  I can confirm this is hapening by looking at my httpd logs.

I've dropped some debug code into StickyNotesOAuthUserProvider.php (specifically in retrieveByCredentials), but I don't see it getting called.  I don't see any errors in the httpd error log or the Laravel log.  

My config:
Centos 7
nginx 1.6.1
php-fpm 5.4.16

Also, a few feature requests:  

If it would be possible to restrict access to the app based on the domain of the OAuth user's email address, that would be phenomenal.   We are hoping to use Sticky Notes as a private in-company pastebin, hosted on a globally-accessible webserver and protected by OAuth.  In this case we want to limit access to the app to only people who are at our company and have valid credentials.

Also, it would be nice if there was some mechanism to test Oauth from within the Authentication Settings menu, prior to enabling it site-wide.  Having to touch the DB and clear the cache after enabling a broken OAuth config is annoying :)

Thanks again!

**Comment by sayakb** [comment]
Closing this issue, it can be tracked on the linked issue (which currently has no response).

**Comment by eschwim** [comment]
Dropped some debug code in Laravel and Lusitanian; it turns out that Nginx wasn't passing get params to php-fpm.  Since it looks like the Lusitanian OAuth lib is the only thing in the entire Sticky Notes install that uses get (vs post) params, this went completely unnoticed.  Changing my Nginx config to the below fixed Oauth for me (note that the `try_files` line has been changed to include `$args`):

```
server {                                          
    listen 443;
    server_name notes.myserver.com;
    root /var/www/sticky-notes/public;
    index index.php;

    try_files $uri $uri/ /index.php?$1$args;

    access_log /data/nginx/notes_access_log;
    error_log /data/nginx/notes_error_log;

    location ~ .*\.php {                                                  
        fastcgi_pass   unix:/var/run/php-fpm/sock;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;                                    
    }

}
```

**Comment by tessus** [comment]
I'm using Apache and there's nothing in the config that would suggest that get parameters are not handled correctly.
It's still not working in my environment.

**Comment by eschwim** [comment]
I added this to the top of my public/index.php (obviously your path to `app/storage` may differ; the appropriate thing would be to call storage_path(), but we want to do this before Laravel initializes, since it blows away many of the PHP super globals, like $_REQUEST):

```
file_put_contents(
  "/var/www/html/sticky-notes/app/storage/logs/oauth.txt", 
  print_r($_REQUEST, TRUE), 
  FILE_APPEND
);
```

If you go through the Google OAuth process and don't see anything similar to this in your log:

```
Array
(
    [code] => 4/ZC1jciX7lIiTVFuhK2EDP3dHTVZFfCkL3Q48d1P15cs.sjMy9C2vly0REnp6UAPFm0GEvsh5lgI
)
```

...then you are very likely running into the same problem that I had.  If you *do* have a `code` GET param set, then we may have divergent problems :(

**Comment by tessus** [comment]
Yes, I do get the the GET data. I think that's why @sayakb opened the bug https://github.com/Lusitanian/PHPoAuthLib/issues/337
But thanks for the info. At least I know our problem is not the same. :-)
