### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Illumicode** [sayakb/sticky-notes#191]
Hi!
When trying to install sticky notes, i get a 404 Not Found error("The requested URL /sticky-notes-1.9/public/setup/install was not found on this server."). (the paths should be working fine as I didn't move any of the files).
Any ideas?

**Comment by Lartza** [comment]
I'm basically having the same problem. I have sticky-notes residing in /var/www/paste, apache is set "Alias /paste /var/www/paste/public" and when I go to /paste it redirects me to /paste/setup/install and Apache throws an /var/www/paste/public/index.php

**Comment by sayakb** [comment]
Try appending index.php to your URL. It seems like URL rewriting isn't working for your virtual host.

**Comment by Illumicode** [comment]
That fixed the problem. Thanks.
